services:
  web:
    image: ${DOCKER_REGISTRY:-ghcr.io}/${DOCKER_USERNAME:-marcus}/${DOCKER_IMAGE:-inquiry}:${DOCKER_TAG:-web-latest}
    ports:
      - "${PORT:-5020}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=/app/db/inquiry.db
      - ORIGIN=http://haplab.com
      - JWT_SECRET=${JWT_SECRET:-inquiry_jwt_secret_key_2025}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    volumes:
      - ./db:/app/db:delegated
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"